# Exported from Render on 2024-09-06T19:48:04Z
services:
- type: web
  name: Patrimoine_CRUD
  runtime: node
  repo: https://github.com/Kiku-no-Jo/Patrimoine_CRUD
  plan: free
  region: oregon
  buildCommand: npm install && npm run build
  startCommand: npm run start
version: "1"
