version: "1"
services:
  - type: web
    name: Patrimoine_CRUD_Frontend
    runtime: node
    repo: https://github.com/Kiku-no-Jo/Patrimoine_CRUD
    plan: free
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000  # Adjust the frontend port if needed

  - type: web
    name: Patrimoine_CRUD_Backend
    runtime: node
    repo: https://github.com/Kiku-no-Jo/Patrimoine_CRUD
    plan: free
    region: oregon
    buildCommand: cd backend && npm install
    startCommand: cd backend && node ./server.js
    envVars:
      - key: PORT
        value: 5000
